"""Serialisable dataclasses for campaign-level reports.

These shapes are stable wire/disk contracts — they are written to
`artifacts/reports/` as JSON and consumed by the paper supplement renderer.
Field names are intentionally close to the v2 plan §11A spec so that an
external reader can match them to the published schema without re-reading
source code.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any


@dataclass(frozen=True)
class FlowExplanationRecord:
    """Per-flow explanation entry — the input grain for campaign aggregation.

    Fields
    ──────
    flow_id          opaque identifier (typically row index in the test split)
    src_ip / dst_ip  endpoint identifiers; campaigns are grouped on these
    window_start     ISO 8601 timestamp of the first flow in the source window
    stl_technique    MITRE technique ID returned by STL classifier
                     (None if no formula fired on the window).
    top_causal_features
                     ordered list of feature names from Causal Shapley Layer A
    present_concepts
                     list of concept names that fired in Layer C, e.g.
                     ["BruteForce", "DataExfiltration"].
    anomaly_score    fused AE+IF ensemble score for this flow

    Notes
    ─────
    No optional fields are quietly dropped at serialisation; render.py uses
    ``asdict`` which preserves all keys including null values.
    """

    flow_id: str
    src_ip: str
    dst_ip: str
    window_start: str
    stl_technique: str | None
    top_causal_features: list[str]
    present_concepts: list[str]
    anomaly_score: float

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class CampaignReport:
    """SOC-style summary of a host-pair attack window.

    Generated by :func:`reporting.campaign.aggregate_campaigns` over a list of
    :class:`FlowExplanationRecord`.  Designed to fit one row of the paper
    supplement table (plan §11A acceptance criterion).
    """

    campaign_id: str
    src_ip: str
    dst_ip: str
    window_start: str
    window_end: str
    flow_count: int
    dominant_stl_techniques: list[str]
    dominant_concepts: list[str]
    top_causal_features: list[str]
    summary: str
    max_anomaly_score: float = 0.0
    mean_anomaly_score: float = 0.0
    contributing_flow_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
