"""
Generate the remaining XAI-related figures for the paper.

Produces (under artifacts/):
  fig_concept_activation.png        — Layer C activation heatmap
  fig_adversarial_stability.png     — A1/A2/A4/A5 Lipschitz bar chart
  fig_shap_variants.png             — interventional vs asymmetric vs cc-shapley
  fig_family_detection.png          — per-family TPR bar chart
  fig_cf_pareto.png                 — feasibility vs proximity scatter (A2-A5)
  fig_dag_sensitivity.png           — 500-flow flip/remove/PC rho
  fig_faithfulness_per_family.png   — causal vs vanilla sufficiency
  fig_dag_diagram.tex               — LaTeX block for existing nf_dag_v1.png

And the matching LaTeX figure blocks under artifacts/results_tables/.

Usage:
    python scripts/gen_remaining_xai_figures.py
"""
from __future__ import annotations
import json
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import Normalize

matplotlib.rcParams.update({
    "font.family": "serif",
    "font.size": 8,
    "axes.labelsize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "axes.linewidth": 0.6,
    "xtick.major.width": 0.6,
    "ytick.major.width": 0.6,
})

ROOT     = Path(__file__).resolve().parents[1]
ART      = ROOT / "artifacts"
TEX_DIR  = ART / "results_tables"

# A consistent qualitative palette across all figures.
PAL = {
    "causal":   "#2166ac",   # blue   — causal Shapley / A2 / A4
    "vanilla":  "#d6604d",   # red    — vanilla KernelSHAP / DiCE / A0
    "random":   "#999999",   # grey   — random DAG (negative control)
    "concept":  "#5aae61",   # green  — concept abduction / A4
    "high":     "#b2182b",   # dark red for high values in heatmaps
    "low":      "#f7f7f7",
}


def _save(fig: plt.Figure, name: str) -> Path:
    out = ART / name
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"  → {out.relative_to(ROOT)}")
    return out


def _write_tex(name: str, body: str) -> Path:
    out = TEX_DIR / name
    out.write_text(body)
    print(f"  → {out.relative_to(ROOT)}")
    return out


# ════════════════════════════════════════════════════════════════════════════
# 1.  Layer C concept activation heatmap
# ════════════════════════════════════════════════════════════════════════════

def fig_concept_activation():
    print("[1] Layer C concept activation heatmap")
    df = pd.read_csv(ART / "module5c_family_activation_rates.csv")
    fidelity = pd.read_csv(ART / "module5c_family_fidelity.csv")

    families = df["family"].tolist()
    concepts = [c for c in df.columns if c != "family"]
    mat = df[concepts].to_numpy()

    fig, ax = plt.subplots(figsize=(4.5, 2.6))
    norm = Normalize(vmin=0, vmax=1)
    im = ax.imshow(mat, cmap="YlGnBu", norm=norm, aspect="auto",
                   interpolation="nearest")

    ax.set_xticks(np.arange(len(concepts)))
    ax.set_xticklabels(concepts, rotation=0, fontsize=7.5)
    ax.set_yticks(np.arange(len(families)))
    ax.set_yticklabels(families, fontsize=7)

    for i in range(len(families)):
        for j in range(len(concepts)):
            v = mat[i, j]
            ax.text(j, i, f"{v:.2f}", ha="center", va="center",
                    fontsize=7,
                    color="white" if v > 0.55 else "black")

    cbar = fig.colorbar(im, ax=ax, fraction=0.04, pad=0.02)
    cbar.set_label("Activation rate", fontsize=7)
    cbar.ax.tick_params(labelsize=6.5)

    ax.set_xlabel("MITRE-aligned concept")
    ax.set_ylabel("Attack family")
    ax.set_title("Layer C — concept activation per family "
                 f"(mean fidelity = {fidelity['fidelity'].mean():.3f})",
                 fontsize=8, pad=4)
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.set_xticks(np.arange(len(concepts)) - 0.5, minor=True)
    ax.set_yticks(np.arange(len(families)) - 0.5, minor=True)
    ax.grid(which="minor", color="white", linewidth=0.5)
    ax.tick_params(which="minor", bottom=False, left=False)

    fig.tight_layout(pad=0.4)
    _save(fig, "fig_concept_activation.png")

    _write_tex("fig_concept_activation.tex", r"""% Layer C concept activation heatmap.
% Place in §5.6 (Concept Abduction) or §5 right after Tab. tab:cf_metrics.
% Generated by:  python scripts/gen_remaining_xai_figures.py

\begin{figure}[t]
  \centering
  \includegraphics[width=\columnwidth]{fig_concept_activation}
  \caption{%
    Layer~C (Concept Abduction) activation rates per attack family on
    \mbox{NF-CSE-CIC-IDS2018-v2}.
    Each cell is the fraction of family flows that activate a given
    MITRE-aligned concept: BruteForce (T1110), DataExfiltration (T1041),
    ScanBehaviour (T1046).
    Brute-force families fire cleanly on the BruteForce concept
    ($\geq 0.94$) and remain silent on the other two; Bot and
    Infiltration jointly fire the Scan and DataExfil concepts,
    reflecting their multi-phase TTP profile.
    Mean target-concept fidelity is $0.998$, with rank stability $1.0$
    across all three targets (W18 gate, Tab.~\ref{tab:concept_abduction}).%
  }
  \label{fig:concept_activation}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# 2.  NF-DAG-v1 diagram (LaTeX block only — PNG already exists)
# ════════════════════════════════════════════════════════════════════════════

def fig_dag_diagram():
    print("[2] NF-DAG-v1 diagram LaTeX block")
    _write_tex("fig_dag_diagram.tex", r"""% NF-DAG-v1 diagram (PNG already exists at artifacts/nf_dag_v1.png).
% Place in §3 (Methodology) or §4 (NF-DAG-v1 Construction).

\begin{figure}[t]
  \centering
  \includegraphics[width=\columnwidth]{nf_dag_v1}
  \caption{%
    NF-DAG-v1: the frozen NetFlow-v2 causal DAG used by all three XAI
    layers.
    Nodes are the 41 retained NF-v2 features; directed edges encode
    expert-elicited causal relations (e.g., \texttt{PROTOCOL} $\to$
    \texttt{TCP\_FLAGS}, \texttt{IN\_BYTES} $\to$
    \texttt{RETRANSMITTED\_IN\_BYTES}).
    The DAG was validated against the PC algorithm under three
    perturbations (flip-5, remove-5, pc-replace) on 500 attack flows;
    rank-correlation $\rho \geq 0.84$ on all three perturbations
    confirms causal Shapley attributions are robust to DAG noise
    (Fig.~\ref{fig:dag_sensitivity}, Tab.~\ref{tab:causal_shap}).%
  }
  \label{fig:nf_dag_v1}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# 3.  Adversarial stability bar chart (Lipschitz under Slack-2020 attack)
# ════════════════════════════════════════════════════════════════════════════

def fig_adversarial_stability():
    print("[3] Adversarial stability bar chart")
    df = pd.read_csv(ART / "module_x4_adversarial_stability.csv")

    short = {
        "A1 vanilla KernelSHAP (Slack 2020 baseline)": "A1\nvanilla\nKernelSHAP",
        "A2 Causal Shapley over NF-DAG-v1 (Ng 2025)": "A2\nCausal\nShapley",
        "A4 full pipeline (Causal Shapley + concept)": "A4\nFull",
        "A5 random DAG (negative control)": "A5\nRandom\nDAG",
    }
    df["label"] = df["method"].map(short)
    df["colour"] = [PAL["vanilla"], PAL["causal"], PAL["concept"], PAL["random"]]

    fig, ax = plt.subplots(figsize=(3.6, 3.0))
    x = np.arange(len(df))
    bars = ax.bar(x, df["lipschitz_mean"], yerr=df["lipschitz_std"],
                  color=df["colour"], capsize=3, linewidth=0,
                  error_kw={"linewidth": 0.7, "ecolor": "#333"})
    for bar, m in zip(bars, df["lipschitz_mean"]):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.02, f"{m:.3f}",
                ha="center", va="bottom", fontsize=6.5)

    a1 = float(df.loc[df["method"].str.startswith("A1"), "lipschitz_mean"].iloc[0])
    a2 = float(df.loc[df["method"].str.startswith("A2"), "lipschitz_mean"].iloc[0])
    pct = (a1 - a2) / a1 * 100
    ax.annotate(f"−{pct:.0f}%", xy=(1, a2), xytext=(0.5, (a1 + a2) / 2),
                arrowprops=dict(arrowstyle="->", lw=0.7, color="black"),
                fontsize=8, fontweight="bold", ha="center")

    ax.set_xticks(x)
    ax.set_xticklabels(df["label"], fontsize=6.5)
    ax.set_ylabel("Lipschitz constant (lower is more stable)")
    ax.set_title("Explanation stability under Slack-2020 perturbation\n(n=12 attack flows)",
                 fontsize=8, pad=4)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="y", linewidth=0.4, color="grey", alpha=0.4, zorder=0)
    ax.set_axisbelow(True)
    ax.set_ylim(0, max(df["lipschitz_mean"] + df["lipschitz_std"]) * 1.25)

    fig.tight_layout(pad=0.4)
    _save(fig, "fig_adversarial_stability.png")

    _write_tex("fig_adversarial_stability.tex", r"""% Adversarial stability bar chart.
% Place in §5.7 (Adversarial Robustness) — companion to Tab. tab:adversarial_stability.

\begin{figure}[t]
  \centering
  \includegraphics[width=0.85\columnwidth]{fig_adversarial_stability}
  \caption{%
    Explanation stability under the Slack 2020 adversarial perturbation
    benchmark.
    Lipschitz constant is the per-flow change in the top-3 feature
    attribution under $\|\delta\|_2 \leq 0.1$ noise (n=12 attack flows).
    Switching from vanilla KernelSHAP (A1) to Causal Shapley over
    NF-DAG-v1 (A2) lowers the cross-cell mean Lipschitz constant by
    $\sim$23\% (per-cell paired median improvement 29.1\%, 11/12 cells
    improve; Tab.~\ref{tab:adversarial_stability}),
    confirming that conditioning attributions on the causal DAG yields
    more stable explanations under the same perturbation budget.
    The random-DAG negative control (A5) achieves similar stability,
    which is expected --- any conditioning structure smooths
    attributions; what NF-DAG-v1 adds is causal \emph{feasibility}
    (Tab.~\ref{tab:feasibility_ablation}), not stability alone.%
  }
  \label{fig:adv_stability}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# 4.  Causal Shapley variant comparison (interventional vs asymmetric vs cc)
# ════════════════════════════════════════════════════════════════════════════

def fig_shap_variants():
    print("[4] Causal Shapley variant comparison")
    df = pd.read_csv(ART / "causal_shapley_variant_check.csv")
    methods = df["method"].tolist()
    sums = df["sum_phi"].tolist()
    gaps = df["efficiency_gap"].abs().tolist()
    top_abs = df["top_abs_phi"].tolist()
    l1_delta = df["cc_vs_interventional_l1_delta"].tolist()

    fig, axes = plt.subplots(1, 2, figsize=(6.4, 2.6))
    x = np.arange(len(methods))
    colours = [PAL["causal"], "#67a9cf", "#92c5de"]

    # Panel A: top |phi| comparison
    bars = axes[0].bar(x, top_abs, color=colours, linewidth=0)
    for bar, v in zip(bars, top_abs):
        axes[0].text(bar.get_x() + bar.get_width() / 2,
                     bar.get_height() + 0.01, f"{v:.3f}",
                     ha="center", va="bottom", fontsize=6.5)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(methods, rotation=15, fontsize=7, ha="right")
    axes[0].set_ylabel(r"Top $|\varphi|$ (RETRANS\_IN\_BYTES)")
    axes[0].set_title("(a) Magnitude on top feature", fontsize=8, pad=3)

    # Panel B: efficiency gap (|gap| relative to baseline)
    bars = axes[1].bar(x, gaps, color=colours, linewidth=0)
    for bar, v in zip(bars, gaps):
        axes[1].text(bar.get_x() + bar.get_width() / 2,
                     bar.get_height() + 1e-4, f"{v:.4f}",
                     ha="center", va="bottom", fontsize=6.5)
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(methods, rotation=15, fontsize=7, ha="right")
    axes[1].set_ylabel(r"$|$Efficiency gap$|$")
    axes[1].set_title("(b) Efficiency axiom violation", fontsize=8, pad=3)

    for ax in axes:
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(axis="y", linewidth=0.4, color="grey", alpha=0.4, zorder=0)
        ax.set_axisbelow(True)

    fig.suptitle("Causal Shapley variant comparison "
                 r"(single representative DoS-Hulk flow, identical DAG)",
                 fontsize=8.5, y=1.04)
    fig.tight_layout(pad=0.4)
    _save(fig, "fig_shap_variants.png")

    _write_tex("fig_shap_variants.tex", r"""% Causal Shapley variant comparison.
% Place in §3.3 (Layer A choices) or §5.2 supplemental discussion.

\begin{figure}[t]
  \centering
  \includegraphics[width=\columnwidth]{fig_shap_variants}
  \caption{%
    Causal Shapley variant comparison on a representative DoS-Hulk flow:
    interventional, asymmetric, and CC-Shapley (Heskes 2020) all share
    the same NF-DAG-v1 background distribution.
    (a) Magnitude of the top feature
    (\texttt{RETRANSMITTED\_IN\_BYTES}).
    All three agree to within $\sim$4\%, indicating the choice of causal
    Shapley variant has limited impact on top-feature ranking.
    (b) Efficiency-axiom violation (lower is better):
    all variants achieve $|\text{gap}| \leq 0.021$, well below the W13
    gate of $0.05$ (Tab.~\ref{tab:causal_shap}).
    We adopt the \textit{interventional} variant in the main pipeline
    because it has the cleanest Pearl-style interpretation and matches
    Heskes 2020 \texttt{shapr} numerics to within 1.75\% MAPE
    (Tab.~\ref{tab:causal_shap}, last row).%
  }
  \label{fig:shap_variants}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# 5.  Per-family detection rate bar chart
# ════════════════════════════════════════════════════════════════════════════

def fig_family_detection():
    print("[5] Per-family detection rate bar chart")
    df = pd.read_csv(ART / "family_metrics.csv")
    df = df[df["Attack"] != "Benign"].copy()
    df = df.sort_values("DetectionRate_TPR", ascending=True)

    fig, ax = plt.subplots(figsize=(4.6, 3.6))
    y = np.arange(len(df))
    tpr = df["DetectionRate_TPR"].values

    colours = ["#b2182b" if t < 0.50 else
               "#fdae61" if t < 0.80 else
               "#1a9850" for t in tpr]
    bars = ax.barh(y, tpr, color=colours, linewidth=0, height=0.7)
    for bar, t, n in zip(bars, tpr, df["AttackCount"]):
        ax.text(min(t + 0.012, 1.005),
                bar.get_y() + bar.get_height() / 2,
                f"{t:.3f}  (n={int(n):,})",
                va="center", fontsize=6.5)

    ax.set_yticks(y)
    ax.set_yticklabels(df["Attack"], fontsize=7)
    ax.set_xlim(0, 1.18)
    ax.set_xlabel("Detection rate (TPR)")
    ax.axvline(0.90, color="grey", linestyle=":", linewidth=0.7)
    ax.text(0.90, len(df) - 0.5, " 0.90", fontsize=6, color="grey",
            va="center")

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="x", linewidth=0.4, color="grey", alpha=0.4, zorder=0)
    ax.set_axisbelow(True)
    ax.set_title("Detection rate per attack family\n(NF-CSE-CIC-IDS2018-v2 test split)",
                 fontsize=8, pad=4)

    fig.tight_layout(pad=0.4)
    _save(fig, "fig_family_detection.png")

    _write_tex("fig_family_detection.tex", r"""% Per-family detection rate bar chart.
% Place in §5.1 (Detection) — companion to Tab. tab:campaign_summary.

\begin{figure}[t]
  \centering
  \includegraphics[width=0.92\columnwidth]{fig_family_detection}
  \caption{%
    Detection rate (TPR) per attack family on the
    NF-CSE-CIC-IDS2018-v2 test split, sorted ascending.
    Green bars denote families above the 0.90 detection target;
    amber: between 0.50--0.90; red: below 0.50.
    Eleven of fourteen families exceed 0.90 (volumetric DoS, DDoS,
    brute-force, and SlowHTTP); two long-tail families
    (Bot, Infiltration) remain partially missed and are the focus of
    Layer~C concept-abduction recovery
    (Fig.~\ref{fig:concept_activation}).%
  }
  \label{fig:family_detection}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# 6.  CF Pareto scatter — feasibility vs proximity per method×dataset
# ════════════════════════════════════════════════════════════════════════════

def fig_cf_pareto():
    print("[6] CF Pareto scatter (feasibility vs proximity)")
    df = pd.read_csv(TEX_DIR / "table_cf_metrics.csv")
    # parse method / dataset out of the "Method" column
    parts = df["Method"].str.split("/", expand=True)
    df["method"]  = parts[0]
    df["dataset"] = parts[1]
    df = df.rename(columns={"Feasibility_mean": "feas",
                             "Proximity_mean": "prox"})

    method_styles = {
        "A2_causal_shap": {"color": PAL["causal"],  "marker": "o", "label": "A2 Causal SHAP"},
        "A3_moocf":       {"color": "#67a9cf",      "marker": "s", "label": "A3 NSGA-II"},
        "A4_full":        {"color": PAL["concept"], "marker": "^", "label": "A4 Full"},
        "A5_random_dag":  {"color": PAL["random"],  "marker": "x", "label": "A5 Random DAG"},
    }

    fig, ax = plt.subplots(figsize=(4.2, 3.3))
    for method, style in method_styles.items():
        sub = df[df["method"] == method]
        ax.scatter(sub["prox"], sub["feas"],
                   s=70, marker=style["marker"], color=style["color"],
                   label=style["label"], edgecolor="white", linewidth=0.6,
                   alpha=0.85, zorder=3)

    ax.axhline(0.80, color="grey", linestyle=":", linewidth=0.7)
    ax.text(ax.get_xlim()[1] * 0.97, 0.81, "feas. target = 0.80",
            ha="right", fontsize=6.5, color="grey")

    ax.set_xlabel(r"Proximity $L_2$ (lower is better)")
    ax.set_ylabel("Causal feasibility (NF-DAG-v1)")
    ax.set_title("Counterfactual quality across methods × datasets\n(4 methods × 4 datasets = 16 points)",
                 fontsize=8, pad=4)
    ax.set_ylim(0.6, 1.02)

    ax.legend(fontsize=6.5, loc="lower right", frameon=True,
              edgecolor="grey", framealpha=0.9)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(linewidth=0.4, color="grey", alpha=0.4, zorder=0)
    ax.set_axisbelow(True)

    fig.tight_layout(pad=0.4)
    _save(fig, "fig_cf_pareto.png")

    _write_tex("fig_cf_pareto.tex", r"""% CF Pareto-front scatter (feasibility vs proximity).
% Place in §5.5 (Counterfactual Explainability) — companion to Tab. tab:cf_metrics.

\begin{figure}[t]
  \centering
  \includegraphics[width=0.88\columnwidth]{fig_cf_pareto}
  \caption{%
    Counterfactual quality across methods and datasets.
    Each point is one $(\text{method}, \text{dataset})$ cell from
    Tab.~\ref{tab:cf_metrics}; closer to the top-left is better
    (high feasibility, low proximity).
    A5 (random-DAG negative control) collapses to feasibility
    $\sim$0.65 across all four datasets despite identical NSGA-II
    machinery, confirming that the feasibility gain in A3/A4 is driven
    by NF-DAG-v1 specifically, not by the search algorithm.
    A2 (Causal Shapley as CF generator) trades sparsity for proximity:
    fewer features changed but slightly lower feasibility.%
  }
  \label{fig:cf_pareto}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# 7.  DAG sensitivity rank correlation chart
# ════════════════════════════════════════════════════════════════════════════

def fig_dag_sensitivity():
    print("[7] DAG sensitivity rank correlation chart")
    with open(ART / "module5a_sensitivity_500flows.json") as f:
        data = json.load(f)
    perts = data["perturbations"]

    labels = list(perts.keys())          # flip_5, remove_5, pc_replace
    rhos   = [perts[k]["rho"] for k in labels]
    pretty = {"flip_5":     "Flip-5\n(reverse 5 edges)",
              "remove_5":   "Remove-5\n(delete 5 edges)",
              "pc_replace": "PC-replace\n(swap for PC-learned)"}
    display_labels = [pretty[k] for k in labels]

    fig, ax = plt.subplots(figsize=(3.8, 2.7))
    x = np.arange(len(labels))
    bars = ax.bar(x, rhos, color=PAL["causal"], width=0.55, linewidth=0)
    for bar, r in zip(bars, rhos):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.01, f"{r:.3f}",
                ha="center", va="bottom", fontsize=7)

    ax.axhline(data["rho_threshold"], color="grey", linestyle=":",
               linewidth=0.7)
    ax.text(len(labels) - 0.5, data["rho_threshold"] + 0.005,
            f" gate = {data['rho_threshold']:.2f}",
            fontsize=6.5, color="grey", ha="right")

    ax.set_xticks(x)
    ax.set_xticklabels(display_labels, fontsize=7)
    ax.set_ylabel(r"Spearman $\rho$ vs original NF-DAG-v1")
    ax.set_ylim(0, 1.05)
    ax.set_title(f"Causal Shapley sensitivity to DAG noise (n={data['n_flows']} flows)",
                 fontsize=8, pad=4)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="y", linewidth=0.4, color="grey", alpha=0.4, zorder=0)
    ax.set_axisbelow(True)

    fig.tight_layout(pad=0.4)
    _save(fig, "fig_dag_sensitivity.png")

    _write_tex("fig_dag_sensitivity.tex", r"""% DAG sensitivity rank-correlation chart.
% Place in §5.2 or §5.3 — companion to W13 sensitivity rows of Tab. tab:causal_shap.

\begin{figure}[t]
  \centering
  \includegraphics[width=0.85\columnwidth]{fig_dag_sensitivity}
  \caption{%
    Causal Shapley sensitivity to NF-DAG-v1 noise (500-flow paper-grade
    run, Gap~4-A).
    Each bar is the Spearman rank-correlation between Shapley
    attributions computed with the original NF-DAG-v1 and with the
    perturbed DAG, across all $\sim$$2.05 \times 10^4$ feature--flow
    pairs.
    All three perturbations exceed the $\rho \geq 0.80$ gate,
    indicating that explanation rankings are robust to local edge
    perturbations and to a fully data-driven DAG replacement
    (PC-replace, $\rho = 0.90$).%
  }
  \label{fig:dag_sensitivity}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# 8.  Faithfulness per family: causal vs vanilla sufficiency
# ════════════════════════════════════════════════════════════════════════════

def fig_faithfulness_per_family():
    print("[8] Faithfulness per family (causal vs vanilla)")
    df = pd.read_csv(ART / "module5a_faithfulness_smoke.csv")

    families = df["attack_family"].tolist()
    causal   = df["causal_sufficiency"].tolist()
    vanilla  = df["vanilla_sufficiency"].tolist()

    fig, ax = plt.subplots(figsize=(4.0, 2.8))
    x = np.arange(len(families))
    w = 0.35
    b1 = ax.bar(x - w / 2, causal,  width=w, color=PAL["causal"],
                label="Causal Shapley", linewidth=0)
    b2 = ax.bar(x + w / 2, vanilla, width=w, color=PAL["vanilla"],
                label="Vanilla KernelSHAP", linewidth=0)
    for bars, vals in [(b1, causal), (b2, vanilla)]:
        for bar, v in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 0.015, f"{v:.2f}",
                    ha="center", va="bottom", fontsize=6.5)

    short = {"DDOS attack-HOIC": "HOIC",
             "DoS attacks-Hulk": "Hulk",
             "DDoS attacks-LOIC-HTTP": "LOIC-HTTP"}
    ax.set_xticks(x)
    ax.set_xticklabels([short.get(f, f) for f in families], fontsize=8)
    ax.set_ylabel("ERASER sufficiency (top-12)")
    ax.set_ylim(0, 1.15)
    ax.set_title("Per-family faithfulness: Causal Shapley vs vanilla KernelSHAP",
                 fontsize=8, pad=4)
    ax.legend(fontsize=7, loc="upper right", frameon=True,
              edgecolor="grey", framealpha=0.9)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="y", linewidth=0.4, color="grey", alpha=0.4, zorder=0)
    ax.set_axisbelow(True)

    fig.tight_layout(pad=0.4)
    _save(fig, "fig_faithfulness_per_family.png")

    _write_tex("fig_faithfulness_per_family.tex", r"""% Per-family ERASER sufficiency: causal vs vanilla.
% Place in §5.2 next to Tab. tab:faithfulness — makes the LOIC-HTTP collapse visible.

\begin{figure}[t]
  \centering
  \includegraphics[width=0.78\columnwidth]{fig_faithfulness_per_family}
  \caption{%
    Per-family ERASER sufficiency (top-12 features, $k=3$ flows per
    family, 1\,000-row attack pool) for Causal Shapley over NF-DAG-v1
    versus vanilla KernelSHAP.
    Causal Shapley narrowly beats vanilla KernelSHAP on volumetric
    attacks (HOIC, Hulk) and \emph{catastrophically} beats it on
    DDoS-LOIC-HTTP (0.96 vs 0.04), where vanilla KernelSHAP places top
    mass on features that fail to reproduce the anomaly score.
    This single case is the strongest faithfulness evidence for the
    causal formulation: vanilla SHAP is not just less stable
    (Fig.~\ref{fig:adv_stability}); under some attack families it is
    \emph{wrong}.%
  }
  \label{fig:faithfulness_per_family}
\end{figure}
""")


# ════════════════════════════════════════════════════════════════════════════
# main
# ════════════════════════════════════════════════════════════════════════════

def main():
    print(f"Writing figures and LaTeX blocks to {ART} and {TEX_DIR}")
    fig_concept_activation()
    fig_dag_diagram()
    fig_adversarial_stability()
    fig_shap_variants()
    fig_family_detection()
    fig_cf_pareto()
    fig_dag_sensitivity()
    fig_faithfulness_per_family()
    print("Done.")


if __name__ == "__main__":
    main()
