"""Human-readable narrative supplement.

Reads the campaign artifacts produced by
``generate_campaign_examples.py`` / ``generate_campaign_production.py`` and
emits three-part analyst narratives (Detection / Reasoning / Suggested Action)
for every campaign, plus a curated LaTeX case-study box for the paper body.

The narratives are generated by :func:`caushap_nids.reporting.narrate_campaign`
— a deterministic, template-based renderer (no external LLM API), so the output
is fully reproducible from the campaign JSON.

Outputs
-------
- ``artifacts/reports/narratives_full.json``   — every campaign + 3-part narrative
- ``artifacts/reports/narratives_full.md``     — human-readable supplement
- ``artifacts/results_tables/table_narrative_casestudy.tex`` — paper-body box

If ``campaigns_example.json`` is also present, an ``narratives_example.{json,md}``
pair is written alongside.

Run from project root:
    .venv/bin/python scripts/generate_narratives.py
"""
from __future__ import annotations

import json
from pathlib import Path

from caushap_nids.reporting import CampaignReport, narrate_campaign
from caushap_nids.reporting.narrate import _MITRE_DESCRIPTIONS

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "artifacts"
OUT_DIR = ARTIFACTS / "reports"
TABLES_DIR = ARTIFACTS / "results_tables"


# Representative technique classes for the paper-body case-study box.
# One campaign (highest peak score) is selected per class, up to 3 classes.
_CASE_CLASSES: list[tuple[str, set[str]]] = [
    ("Credential Brute Force", {"T1110", "T1110.001", "T1110.004"}),
    ("Denial of Service", {"T1498", "T1499"}),
    ("Command & Control / Exfiltration", {"T1071", "T1041"}),
    ("Network Service Discovery", {"T1046"}),
]

# Preferred campaigns for the paper-body box — these are the SAME three the
# paper already discusses in Table~\ref{tab:campaigns} (§5.10), so the
# structured table and the narrative box tell one coherent story.  Matched by
# src_ip exact value; falls back to _CASE_CLASSES selection if absent
# (e.g. on the example set or another dataset).
_PREFERRED_CASES: list[tuple[str, str]] = [
    ("Credential Brute Force", "host_S_FTP_BruteForce"),
    ("Denial of Service", "host_S_DDOS_attack_LOIC_UDP"),
    ("Command & Control / Exfiltration", "host_S_Bot"),
]


def _load_campaigns(path: Path) -> list[CampaignReport]:
    """Reconstruct CampaignReport objects from a campaigns_*.json artifact."""
    payload = json.loads(path.read_text())
    reports: list[CampaignReport] = []
    for c in payload["campaigns"]:
        reports.append(CampaignReport(
            campaign_id=c["campaign_id"],
            src_ip=c["src_ip"],
            dst_ip=c["dst_ip"],
            window_start=c["window_start"],
            window_end=c["window_end"],
            flow_count=c["flow_count"],
            dominant_stl_techniques=c["dominant_stl_techniques"],
            dominant_concepts=c["dominant_concepts"],
            top_causal_features=c["top_causal_features"],
            summary=c["summary"],
            max_anomaly_score=c.get("max_anomaly_score", 0.0),
            mean_anomaly_score=c.get("mean_anomaly_score", 0.0),
            contributing_flow_ids=c.get("contributing_flow_ids", []),
        ))
    return reports


def _tex(s: str) -> str:
    """Escape a narrative string for LaTeX (char-by-char, no double-escaping)."""
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
        "→": r"$\rightarrow$",
        "—": "---",
        "–": "--",
    }
    return "".join(repl.get(ch, ch) for ch in s)


def _write_narratives(reports: list[CampaignReport], stem: str) -> None:
    """Write narratives_<stem>.{json,md} for a list of campaigns."""
    rows = []
    for r in sorted(reports, key=lambda x: (x.window_start, x.src_ip, x.dst_ip)):
        n = narrate_campaign(r)
        rows.append({
            "campaign_id": r.campaign_id,
            "src_ip": r.src_ip,
            "dst_ip": r.dst_ip,
            "window_start": r.window_start,
            "window_end": r.window_end,
            "flow_count": r.flow_count,
            "max_anomaly_score": r.max_anomaly_score,
            "dominant_stl_techniques": r.dominant_stl_techniques,
            "detection": n.detection,
            "reasoning": n.reasoning,
            "suggested_action": n.suggested_action,
        })

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    json_path = OUT_DIR / f"narratives_{stem}.json"
    with json_path.open("w") as f:
        json.dump({"narratives": rows}, f, indent=2, sort_keys=True)

    md_lines = [
        f"# Human-readable narrative supplement ({stem})",
        "",
        "Generated by `scripts/generate_narratives.py` from "
        f"`artifacts/reports/campaigns_{stem}.json`.",
        "",
        "Narratives are produced by the deterministic, template-based renderer "
        "`caushap_nids.reporting.narrate_campaign` (no external LLM API), so they "
        "are fully reproducible from the campaign records.",
        "",
    ]
    for row in rows:
        md_lines += [
            f"## {row['campaign_id']}",
            "",
            f"**Detection.** {row['detection']}",
            "",
            f"**Reasoning.** {row['reasoning']}",
            "",
            f"**Suggested Action.** {row['suggested_action']}",
            "",
        ]
    (OUT_DIR / f"narratives_{stem}.md").write_text("\n".join(md_lines) + "\n")

    print(f"  wrote {json_path.relative_to(ROOT)}")
    print(f"  wrote {(OUT_DIR / f'narratives_{stem}.md').relative_to(ROOT)}")


def _select_case_studies(reports: list[CampaignReport]) -> list[tuple[str, CampaignReport]]:
    """Pick up to 3 representative campaigns for the paper-body box.

    Prefers the exact campaigns the paper discusses in Table~\\ref{tab:campaigns}
    (see ``_PREFERRED_CASES``); falls back to one highest-scoring campaign per
    technique class for any preferred campaign that is absent.
    """
    selected: list[tuple[str, CampaignReport]] = []
    chosen_ids: set[str] = set()

    for label, src_ip in _PREFERRED_CASES:
        matches = [r for r in reports if r.src_ip == src_ip]
        if not matches:
            continue
        best = max(matches, key=lambda r: r.max_anomaly_score)
        selected.append((label, best))
        chosen_ids.add(best.campaign_id)

    if len(selected) < 3:
        for class_name, techniques in _CASE_CLASSES:
            if any(lbl == class_name for lbl, _ in selected):
                continue
            matches = [
                r for r in reports
                if r.campaign_id not in chosen_ids
                and any(t in techniques for t in r.dominant_stl_techniques)
            ]
            if not matches:
                continue
            best = max(matches, key=lambda r: r.max_anomaly_score)
            selected.append((class_name, best))
            chosen_ids.add(best.campaign_id)
            if len(selected) == 3:
                break

    return selected[:3]


def _write_case_study_latex(reports: list[CampaignReport]) -> None:
    """Emit a paper-body LaTeX box with 2–3 representative narratives."""
    cases = _select_case_studies(reports)
    if not cases:
        print("  (no campaigns matched a case-study class; skipping LaTeX box)")
        return

    lines = [
        "\\begin{table*}[ht]",
        "\\centering",
        "\\small",
        "\\caption{Representative human-readable explanations generated by the "
        "template-based narrator (\\texttt{caushap\\_nids.reporting.narrate}). "
        "Each alert is rendered as a three-part analyst report --- Detection, "
        "Reasoning (causal Shapley features + concept abduction + STL technique), "
        "and a MITRE-keyed Suggested Action. Output is deterministic and "
        "reproducible from the campaign records; no external LLM is used.}",
        "\\label{tab:narrative_casestudy}",
        "\\begin{tabular}{@{}l p{0.82\\linewidth}@{}}",
        "\\toprule",
    ]
    for i, (class_name, r) in enumerate(cases):
        n = narrate_campaign(r)
        tech = r.dominant_stl_techniques[0] if r.dominant_stl_techniques else "—"
        tech_name = _MITRE_DESCRIPTIONS.get(tech, "")
        header = f"Case study {i + 1} — {class_name} ({tech}{', ' + tech_name if tech_name else ''})"
        if i > 0:
            lines.append("\\midrule")
        lines += [
            f"\\multicolumn{{2}}{{@{{}}l}}{{\\textbf{{{_tex(header)}}}}}\\\\",
            "\\midrule",
            f"Detection & {_tex(n.detection)}\\\\[2pt]",
            f"Reasoning & {_tex(n.reasoning)}\\\\[2pt]",
            f"Action & {_tex(n.suggested_action)}\\\\",
        ]
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]

    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    out = TABLES_DIR / "table_narrative_casestudy.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"  wrote {out.relative_to(ROOT)}  ({len(cases)} case studies)")


def main() -> None:
    full_path = OUT_DIR / "campaigns_full.json"
    example_path = OUT_DIR / "campaigns_example.json"

    if not full_path.exists() and not example_path.exists():
        raise SystemExit(
            f"missing campaign artifacts in {OUT_DIR.relative_to(ROOT)}; "
            "run scripts/generate_campaign_production.py first"
        )

    primary: list[CampaignReport] | None = None
    if full_path.exists():
        reports = _load_campaigns(full_path)
        print(f"loaded {len(reports)} campaigns from campaigns_full.json")
        _write_narratives(reports, "full")
        primary = reports

    if example_path.exists():
        reports = _load_campaigns(example_path)
        print(f"loaded {len(reports)} campaigns from campaigns_example.json")
        _write_narratives(reports, "example")
        if primary is None:
            primary = reports

    assert primary is not None
    _write_case_study_latex(primary)


if __name__ == "__main__":
    main()
