"""Gap X-5 — Production campaign-level aggregation.

Extends `generate_campaign_examples.py` (the 8-flow paper-supplement example)
to a full-test-set run plus a paper-supplement summary table with
per-family detection statistics.

Outputs
-------
- `artifacts/reports/campaigns_full.json` — campaign records (200 flows/family cap)
- `artifacts/reports/campaigns_full.md`   — markdown table
- `artifacts/reports/campaign_summary.csv` — per-family stats (detection rate,
                                              FPR, mean score, n_flows)
- `artifacts/results_tables/table_campaign_summary.{tex,csv}` — paper-ready
"""
from __future__ import annotations

import csv
import json
import statistics as st
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "artifacts"
OUT_DIR = ARTIFACTS / "reports"
TABLES_DIR = ARTIFACTS / "results_tables"

# Reuse mappings from the example generator
from generate_campaign_examples import (
    FAMILY_TO_TECHNIQUE,
    FAMILY_TO_CONCEPTS,
    FAMILY_TOP_FEATURES,
    _record_for_flow,
)
from caushap_nids.reporting import (
    aggregate_campaigns,
    campaign_reports_to_markdown,
    campaign_reports_to_json,
)
from caushap_nids.evaluation.table_writer import write_latex_table


def main(n_per_family: int = 200) -> None:
    test_path = ARTIFACTS / "test_results.csv"
    if not test_path.exists():
        raise SystemExit(f"missing: {test_path}")

    df = pd.read_csv(test_path, usecols=["Attack", "ens_score", "y_pred", "Label"])
    df = df.rename(columns={"Label": "y_true"})

    # Per-family detection statistics on the FULL test set (not just sampled flows).
    summary_rows = []
    for fam, group in df.groupby("Attack"):
        if fam == "Benign":
            # FPR for benign baseline
            n_total = len(group)
            n_flagged = int((group["y_pred"] == 1).sum())
            summary_rows.append({
                "family":     fam,
                "role":       "benign",
                "n_total":    n_total,
                "n_flagged":  n_flagged,
                "detection_rate": None,
                "fpr":            round(n_flagged / max(n_total, 1), 4),
                "mean_score": round(float(group["ens_score"].mean()), 4),
                "max_score":  round(float(group["ens_score"].max()), 4),
            })
            continue
        n_total = len(group)
        n_detected = int(((group["y_pred"] == 1) & (group["y_true"] == 1)).sum())
        det_rate = n_detected / max(n_total, 1)
        summary_rows.append({
            "family":     fam,
            "role":       "attack",
            "n_total":    n_total,
            "n_flagged":  n_detected,
            "detection_rate": round(det_rate, 4),
            "fpr":            None,
            "mean_score": round(float(group["ens_score"].mean()), 4),
            "max_score":  round(float(group["ens_score"].max()), 4),
        })

    # Sort: benign first, then attacks by detection rate descending
    summary_rows.sort(key=lambda r: (r["role"] != "benign", -(r["detection_rate"] or 0)))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    # Write per-family summary CSV
    with (OUT_DIR / "campaign_summary.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(summary_rows[0].keys()))
        w.writeheader()
        w.writerows(summary_rows)

    # Build campaign records — predicted-attack flows only
    detected = df[df["y_pred"] == 1].copy()
    base = datetime(2026, 5, 15, 14, 0, 0, tzinfo=timezone.utc)
    records = []
    for fam, group in detected.groupby("Attack"):
        if fam == "Benign":
            continue  # benign predictions are FPs, not a "campaign"
        sample = group.head(n_per_family).reset_index(drop=True)
        for i, row in sample.iterrows():
            records.append(_record_for_flow(len(records), row, base))

    print(f"  built {len(records)} flow records across "
          f"{detected['Attack'].nunique() - (1 if 'Benign' in detected['Attack'].values else 0)} attack families")

    reports = aggregate_campaigns(records, window_minutes=10, min_flows=3)
    print(f"  aggregated to {len(reports)} campaigns "
          f"(window=10min, min_flows=3, n_per_family={n_per_family})")

    md_header = (
        "# Campaign-level explanation supplement (production)\n\n"
        "Generated by `scripts/generate_campaign_production.py` from\n"
        "`artifacts/test_results.csv` (full NF-CSE-CIC-IDS2018-v2 test split).\n"
        f"Cap: {n_per_family} flows per attack family (vs 8 in the example artifact).\n"
        "Endpoint identifiers are synthetic (`host_S_<family>` / `host_D_<family>`) "
        "because NF-v2 strips IPs (Sarhan 2022); the campaign-aggregation logic "
        "is faithful, the IPs are illustrative.\n\n"
        "## Per-family detection summary (full test set)\n\n"
    )
    # Add the summary table inline
    md_summary_lines = ["| Family | Role | N total | Detected/Flagged | Detection rate | FPR | Mean score | Max score |",
                         "|---|---|---:|---:|---:|---:|---:|---:|"]
    for r in summary_rows:
        det = "—" if r["detection_rate"] is None else f"{r['detection_rate']:.4f}"
        fpr = "—" if r["fpr"] is None else f"{r['fpr']:.4f}"
        md_summary_lines.append(
            f"| {r['family']} | {r['role']} | {r['n_total']:,} | {r['n_flagged']:,} | {det} | {fpr} | {r['mean_score']:.4f} | {r['max_score']:.4f} |"
        )
    md_summary = "\n".join(md_summary_lines) + "\n\n"

    md_table = campaign_reports_to_markdown(reports)
    (OUT_DIR / "campaigns_full.md").write_text(md_header + md_summary + "## Top campaigns\n\n" + md_table + "\n")
    campaign_reports_to_json(reports, OUT_DIR / "campaigns_full.json")

    # Paper-supplement LaTeX table
    paper_rows = []
    for r in summary_rows:
        # Add 'method' label for the table_writer (combines family + role)
        det_str = "—" if r["detection_rate"] is None else r["detection_rate"]
        fpr_str = "—" if r["fpr"] is None else r["fpr"]
        paper_rows.append({
            "method": f"{r['family']} [{r['role']}]",
            "family": r["family"],
            "role":   r["role"],
            "n_total": r["n_total"],
            "detected_or_flagged": r["n_flagged"],
            "detection_rate": det_str,
            "fpr": fpr_str,
            "mean_score": r["mean_score"],
        })

    write_latex_table(
        results=paper_rows,
        caption=(
            "Per-family campaign summary on the NF-CSE-CIC-IDS2018-v2 test split. "
            "Detection rate is the fraction of attack flows correctly flagged "
            "($y_{\\text{pred}}{=}1$ and $y_{\\text{true}}{=}1$); benign FPR is the "
            "fraction of benign flows incorrectly flagged. Generated by "
            "\\texttt{scripts/generate\\_campaign\\_production.py}."
        ),
        label="tab:campaign_summary",
        output_path=TABLES_DIR / "table_campaign_summary",
        metric_cols=["n_total", "detected_or_flagged", "detection_rate", "fpr", "mean_score"],
    )

    print(f"\nArtifacts:")
    for p in [OUT_DIR / "campaigns_full.md", OUT_DIR / "campaigns_full.json",
              OUT_DIR / "campaign_summary.csv",
              TABLES_DIR / "table_campaign_summary.tex",
              TABLES_DIR / "table_campaign_summary.csv"]:
        print(f"  {p.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
