#!/usr/bin/env Rscript
# R-side validation of Module 5a causal Shapley implementation.
# Uses shapr v1.0.8 with asymmetric=TRUE, confounding=FALSE to compute
# Heskes (2020) interventional Shapley values on a synthetic 3-feature
# chain-DAG dataset generated by Python (passed as CSV arguments).
#
# Usage:
#   Rscript --vanilla r_causal_shap_validation.R \
#     <background_csv> <test_csv> <output_json>
#
# Reference: Heskes et al. NeurIPS 2020 "Causal Shapley Values"
# shapr docs: asymmetric=TRUE, confounding=FALSE => interventional distribution

suppressPackageStartupMessages({
  library(shapr)
  library(jsonlite)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 3) {
  stop("Usage: Rscript r_causal_shap_validation.R <bg_csv> <test_csv> <out_json>")
}
bg_csv   <- args[1]
test_csv <- args[2]
out_json <- args[3]

# Load data generated by Python (identical rows used in Python comparison)
bg     <- read.csv(bg_csv)     # columns: X1, X2, X3
x_test <- read.csv(test_csv)   # single row: X1, X2, X3

# Linear model: f = 2*X1 + 1.5*X2 + 1.0*X3  (matches Python's val_w)
weights <- c(X1 = 2.0, X2 = 1.5, X3 = 1.0)
y_bg <- as.numeric(as.matrix(bg) %*% weights)
bg_train <- cbind(bg, y_resp = y_bg)
lin_model <- lm(y_resp ~ X1 + X2 + X3, data = bg_train)

phi0_val <- mean(y_bg)  # E[f(background)]

# Chain DAG: X1 -> X2 -> X3  (causal_ordering = strict topological sequence)
causal_ord <- list("X1", "X2", "X3")

# Heskes (2020) interventional Shapley via shapr:
#   asymmetric=TRUE  => only upward-closed coalitions
#   confounding=FALSE => no confounders, uses do-calculus interventional distribution
#   approach="gaussian" => fits multivariate Gaussian for conditional expectations
#   (equivalent to linear SEM for linear-Gaussian data)
ex <- shapr::explain(
  model           = lin_model,
  x_explain       = x_test,
  x_train         = bg,
  approach        = "gaussian",
  phi0            = phi0_val,
  asymmetric      = TRUE,
  causal_ordering = causal_ord,
  confounding     = FALSE,
  n_MC_samples    = 2000,
  verbose         = NULL
)

sv <- ex$shapley_values_est[1, ]

result <- list(
  phi_r = list(
    X1 = as.numeric(sv[["X1"]]),
    X2 = as.numeric(sv[["X2"]]),
    X3 = as.numeric(sv[["X3"]])
  ),
  phi0          = phi0_val,
  n_bg          = nrow(bg),
  shapr_version = as.character(packageVersion("shapr")),
  method        = paste0(
    "shapr v", packageVersion("shapr"),
    " asymmetric=TRUE confounding=FALSE approach=gaussian",
    " (Heskes 2020 interventional Shapley)"
  )
)

write(jsonlite::toJSON(result, auto_unbox = TRUE), out_json)
cat("OK\n")
